### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by devsavage** [Huskehhh/WhitelistSQL#2]
```
[00:42:43] [Craft Scheduler Thread - 1/WARN]: [WhitelistSQL] Plugin WhitelistSQL v1.2 generated an exception while executing task 7
    java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    	at java.lang.String.charAt(String.java:646) ~[?:1.8.0_51]
    	at pro.husk.whitelistsql.utility.UUIDHelper.getUUID(UUIDHelper.java:107) ~[?:?]
    	at pro.husk.whitelistsql.utility.MySQLHelper.lambda$addMemberToWhitelist$0(MySQLHelper.java:24) ~[?:?]
    	at pro.husk.whitelistsql.utility.MySQLHelper$$Lambda$2839/1907770485.run(Unknown Source) ~[?:?]
    	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
    	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-e7dc2f5-a8ec1d6]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
    	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

I fixed this using Gson to transform Mojang's output into a JSONObject and sent that to the readData method. This then led to a couple more out of bounds errors so the readData method needing tweaking on the while loop and character start count. After these changes, everything ran perfect!

I wasn't sure if you were aware of the issue already or if I just happened to get lucky!

**Comment by Huskehhh** [comment]
Yeah this randomly broke for me today as well. I'm currently looking into rewriting to use a cleaner method :)

Thanks for the heads up!
